services:
  vless-proxy:
    container_name: vless-to-http
    build: .
    ports:
      - "9000:9000"   # HTTP proxy
      - "1080:1080"   # SOCKS5 proxy

    volumes:
      - ./vless.conf:/app/vless.conf:ro
    restart: unless-stopped
